name: CI (lint)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: pipenv sync --dev

    - name: Lint with flake8 * plug-ins
      run: pipenv run lint
