name: CI (lint)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install pipenv
      uses: dschep/install-pipenv-action@v1

    - name: Install dependencies
      run: pipenv sync --dev

    - name: Lint with flake8 & plug-ins
      run: pipenv run lint
