name: Flake8 & friends

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  checks:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Pipenv
      uses: dschep/install-pipenv-action@v1

    - name: Install dependencies
      run: pipenv sync --dev

    - name: Lint with Flake8 & friends
      run: pipenv run lint
